FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

COPY RedPoint.Account/*.csproj ./RedPoint.Account/
COPY RedPoint.Middleware/*.csproj ./RedPoint.Middleware/
RUN dotnet restore RedPoint.Account/*.csproj

COPY RedPoint.Account ./RedPoint.Account/
COPY RedPoint.Middleware ./RedPoint.Middleware/
RUN dotnet publish RedPoint.Account/*.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "RedPoint.Account.dll"]
