FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

COPY RedPoint.Admin/*.csproj ./RedPoint.Admin/
RUN dotnet restore RedPoint.Admin/*.csproj

COPY RedPoint.Admin ./RedPoint.Admin/
RUN dotnet publish RedPoint.Admin/*.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "RedPoint.Admin.dll"]
