FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

COPY RedPoint.Chat/*.csproj ./RedPoint.Chat/
COPY RedPoint.Middleware/*.csproj ./RedPoint.Middleware/
COPY RedPoint.Data/*.csproj ./RedPoint.Data/
RUN dotnet restore RedPoint.Chat/*.csproj

COPY RedPoint.Chat ./RedPoint.Chat/
COPY RedPoint.Middleware ./RedPoint.Middleware/
COPY RedPoint.Data ./RedPoint.Data/
RUN dotnet publish RedPoint.Chat/*.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "RedPoint.Chat.dll"]
